/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.bridgelabz.opencsvandgson;

import org.junit.Test;

import static org.junit.Assert.*;

public class OpenCSVReaderTest {
    @Test public void testSomeLibraryMethod() {
    	 OpenCSVReader classUnderTest = new OpenCSVReader();
    }
}
